version: '3.8'

services:
  nestjs-api:
    build: .
    container_name: nestjs_api
    ports:
      - '3000:3000'
    environment:
      - PAGBANK_API_URL=${PAGBANK_API_URL}
      - PAGBANK_API_TOKEN=${PAGBANK_API_TOKEN}
      - DATABASE_HOST=postgres_db
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - GAME_DATABASE_HOST=mariadb_db
      - GAME_DATABASE_PORT=${GAME_DATABASE_PORT}
      - GAME_DATABASE_USERNAME=${GAME_DATABASE_USERNAME}
      - GAME_DATABASE_PASSWORD=${GAME_DATABASE_PASSWORD}
      - GAME_DATABASE_NAME=${GAME_DATABASE_NAME}
      - API_URL=${API_URL}
    depends_on:
      - postgres
      - mariadb
    networks:
      - f3s_network

  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Hayasak1!.,.
      POSTGRES_DB: websitedb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb/postgres:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U admin -d payment_db' ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - f3s_network

  mariadb:
    image: mariadb:10.5
    container_name: mariadb_db
    environment:
      MYSQL_ROOT_PASSWORD: sua_senha_root
      MYSQL_DATABASE: wkotserv_db
      MYSQL_USER: benedicto
      MYSQL_PASSWORD: 428181Abc
    ports:
      - '3306:3306'
    volumes:
      - mariadbdata:/var/lib/mysql
      - ./initdb/mariadb:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'mysqladmin ping -h localhost -u benedicto --password=428181Abc'
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - f3s_network
volumes:
  pgdata:
  mariadbdata:

networks:
  f3s_network:
