version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Hayasak1!.,.
      POSTGRES_DB: payment_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U dev_fernando -d payment_db']
      interval: 30s
      timeout: 10s
      retries: 5
    network_mode: 'bridge'

  mariadb:
    image: mariadb:10.5
    container_name: mariadb_db
    environment:
      MYSQL_ROOT_PASSWORD: sua_senha_root
      MYSQL_DATABASE: wkotserv_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: Hayasak1!.,.
    ports:
      - '3307:3306'
    volumes:
      - mariadbdata:/var/lib/mysql
      - ./initdb/mariadb:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'benedicto',
          '--password=428181Ab#',
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    network_mode: 'bridge'

volumes:
  pgdata:
  mariadbdata:
