version: '3.8'

services:
  nestjs-api:
    build: .
    container_name: nestjs_api
    # ports:
    #   - '3000:3000'
    environment:
      - PAGBANK_API_URL=${PAGBANK_API_URL}
      - PAGBANK_API_TOKEN=${PAGBANK_API_TOKEN}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - GAME_DATABASE_HOST=${GAME_DATABASE_HOST}
      - GAME_DATABASE_PORT=${GAME_DATABASE_PORT}
      - GAME_DATABASE_USERNAME=${GAME_DATABASE_USERNAME}
      - GAME_DATABASE_PASSWORD=${GAME_DATABASE_PASSWORD}
      - GAME_DATABASE_NAME=${GAME_DATABASE_NAME}
      - API_URL=${API_URL}
    depends_on:
      - postgres
      # - mariadb
    # networks:
    #   - f3sgames-network
    network_mode: host

  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Hayasak1!.,.
      POSTGRES_DB: payment_db
    # ports:
    #   - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d payment_db']
      interval: 30s
      timeout: 10s
      retries: 5
    network_mode: host
    # networks:
    #   - f3sgames-network

  # mariadb:
  #   image: mariadb:10.5
  #   container_name: mariadb_db
  #   environment:
  #     MYSQL_ROOT_PASSWORD: sua_senha_root
  #     MYSQL_DATABASE: wkotserv_db
  #     MYSQL_USER: admin
  #     MYSQL_PASSWORD: Hayasak1!.,.
  #   ports:
  #     - '3307:3306'
  #   volumes:
  #     - mariadbdata:/var/lib/mysql
  #     - ./initdb/mariadb:/docker-entrypoint-initdb.d
  #   healthcheck:
  #     test:
  #       [
  #         'CMD',
  #         'mysqladmin',
  #         'ping',
  #         '-h',
  #         'localhost',
  #         '-u',
  #         'admin',
  #         '--password=Hayasak1!.,.',
  #       ]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
  #   network_mode: 'bridge'

  mariadb:
    image: mariadb:10.5
    container_name: mariadb_db
    environment:
      MYSQL_ROOT_PASSWORD: sua_senha_root
      MYSQL_DATABASE: wkotserv_db
      MYSQL_USER: benedicto
      MYSQL_PASSWORD: 428181Abc
    ports:
      - '3307:3306'
    volumes:
      - mariadbdata:/var/lib/mysql
      - ./initdb/mariadb:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'benedicto',
          '--password=428181Abc',
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    network_mode: 'bridge'

volumes:
  pgdata:
  mariadbdata:

