export enum Country {
  Brazil = 'br',
  UnitedStates = 'us',
  UnitedKingdom = 'gb',
  France = 'fr',
  Germany = 'de',
  China = 'cn',
  Russia = 'ru',
  India = 'in',
  Japan = 'jp',
  Canada = 'ca',
  Australia = 'au',
  Mexico = 'mx',
  Italy = 'it',
  Spain = 'es',
  Argentina = 'ar',
  SouthAfrica = 'za',
  SouthKorea = 'kr',
  NewZealand = 'nz',
  SaudiArabia = 'sa',
  Egypt = 'eg',
}
