export enum Towns {
    NO_TOWN = 0,
    TUTORIAL_CITY = 1,
    AB_DENDRIEL = 5,
    CARLIN = 6,
    KAZORDOON = 7,
    THAIS = 8,
    VENORE = 9,
    ANKRAHMUN = 10,
    EDRON = 11,
    FARMINE = 12,
    DARASHIA = 13,
    LIBERTY_BAY = 14,
    PORT_HOPE = 15,
    SVARGROND = 16,
    YALAHAR = 17,
    GRAY_BEACH = 18,
    RATHLETON = 20,
    ISSAVI = 22,
    BOUNAC = 25,
  }
  
  export const TownNameToIdMap: { [key: string]: number } = {
    "NO_TOWN": Towns.NO_TOWN,
    "TUTORIAL_CITY": Towns.TUTORIAL_CITY,
    "AB_DENDRIEL": Towns.AB_DENDRIEL,
    "CARLIN": Towns.CARLIN,
    "KAZORDOON": Towns.KAZORDOON,
    "THAIS": Towns.THAIS,
    "VENORE": Towns.VENORE,
    "ANKRAHMUN": Towns.ANKRAHMUN,
    "EDRON": Towns.EDRON,
    "FARMINE": Towns.FARMINE,
    "DARASHIA": Towns.DARASHIA,
    "LIBERTY_BAY": Towns.LIBERTY_BAY,
    "PORT_HOPE": Towns.PORT_HOPE,
    "SVARGROND": Towns.SVARGROND,
    "YALAHAR": Towns.YALAHAR,
    "GRAY_BEACH": Towns.GRAY_BEACH,
    "RATHLETON": Towns.RATHLETON,
    "ISSAVI": Towns.ISSAVI,
    "BOUNAC": Towns.BOUNAC,
  };
  