-- CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED BY 'Hayasak1!.,.';
-- GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;
-- FLUSH PRIVILEGES;

CREATE USER IF NOT EXISTS 'benedicto'@'localhost' IDENTIFIED BY '428181Abc';
GRANT ALL PRIVILEGES ON *.* TO 'benedicto'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;
