import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('coupons')
export class Coupon {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  code: string; /*
  Coupon code -
  Probably will be generated by the coupon module itself
*/
  @Column()
  influencerName: string;

  @Column()
  influencerEmail: string;

  @Column()
  influencerBirthdate: Date;

  @Column()
  influencerDocument: string;

  @Column()
  pixKey: string;

  @Column()
  socialNetwork: string;

  @Column()
  socialNetworkProfile: string;

  @Column('decimal', { precision: 10, scale: 2 })
  minimumQuote: number;

  @Column({ default: false })
  isActive: boolean; //back-end will take care of this info

  @Column({ type: 'timestamp', default: () => 'CURRENT_TIMESTAMP' })
  createdAt: Date;
}
